version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.11.15-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=justatom
      - RABBITMQ_DEFAULT_PASS=fate
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes:
      - rabbitmqdb:/var/lib/rabbitmq
  most:
    image: most
    container_name: most
    build:
      dockerfile: Dockerfile
    ports:
      - 2222:2222
    depends_on:
      - rabbitmq

volumes:
  rabbitmqdb:
